[telegram]
token = "6778234804:AAFhrIGz4Jk4wOntOkXX_mH2Ek3iS4mT_e0"

[mongodb]
server = "localhost"
port = 27017

[server]
address = "https://yandex-music-bot-production.up.railway.app:5000/"
enabled = true
host = "0.0.0.0"
port = 5000
