[telegram]
token = "6778234804:AAGh0i4rSpr6DH1GiijzCmOgpBzlxEf8Hrs"

[mongodb]
server = "localhost"
port = 27017

[server]
address = "https://yandex-music-bot-production.up.railway.app"
enabled = true
host = "0.0.0.0"
port = 8000